-- =====================================================
-- DIZITALADDA CRM - Complete Consolidated Database Setup
-- PostgreSQL 15+ / 16+ Compatible
-- Includes runtime tables, migrations, indexes, constraints, and reference seeds.
-- Idempotent: safe for a fresh database or an existing installation.
-- =====================================================

BEGIN;

-- Code Generation Sequences
CREATE SEQUENCE IF NOT EXISTS employee_code_seq START WITH 1001;
CREATE SEQUENCE IF NOT EXISTS campaign_code_seq START WITH 1001;
CREATE SEQUENCE IF NOT EXISTS lead_code_seq START WITH 1001;

-- Users Table
CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR(150) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    role            VARCHAR(30) NOT NULL DEFAULT 'COUNSELLOR',
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,
    email_verified  BOOLEAN NOT NULL DEFAULT FALSE,
    profile_image   TEXT,
    last_login      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'SUPER_ADMIN', 'MANAGER', 'COUNSELLOR', 'EMPLOYEE', 'HR', 'TL', 'TRAINER', 'INTERN', 'admin', 'super_admin', 'manager', 'counsellor', 'employee', 'hr', 'tl', 'trainer', 'intern'))
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image TEXT;

-- Departments Table
CREATE TABLE IF NOT EXISTS departments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(150) NOT NULL UNIQUE,
    description     TEXT,
    status          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO departments (department_name, description, status)
VALUES
    ('Sales', 'Sales, lead follow-up, counselling and admissions conversion', TRUE),
    ('Operations', 'Daily business operations, coordination and service delivery', TRUE)
ON CONFLICT (department_name) DO NOTHING;

-- Employees Table
CREATE TABLE IF NOT EXISTS employees (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT UNIQUE REFERENCES users(id) ON DELETE SET NULL,
    employee_code           VARCHAR(30) NOT NULL UNIQUE,
    full_name               VARCHAR(150) NOT NULL,
    email                   VARCHAR(255) NOT NULL UNIQUE,
    mobile                  VARCHAR(20) NOT NULL UNIQUE,
    department_id           BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    reporting_manager_id    BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    designation             VARCHAR(100),
    role                    VARCHAR(30) NOT NULL DEFAULT 'COUNSELLOR',
    employment_type         VARCHAR(30) NOT NULL DEFAULT 'FULL_TIME',
    status                  VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    joining_date            DATE,
    date_of_birth           DATE,
    gender                  VARCHAR(30),
    profile_image           TEXT,
    address                 TEXT,
    emergency_contact_name  VARCHAR(150),
    emergency_contact       VARCHAR(20),
    domain                  VARCHAR(150),
    assigned_domains        JSONB DEFAULT '[]'::jsonb,
    created_by              BIGINT,
    updated_by              BIGINT,
    deleted_by              BIGINT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at              TIMESTAMPTZ,
    is_deleted              BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT employees_role_check CHECK (role IN ('ADMIN', 'SUPER_ADMIN', 'MANAGER', 'COUNSELLOR', 'EMPLOYEE', 'HR', 'TL', 'TRAINER', 'INTERN')),
    CONSTRAINT employees_status_check CHECK (status IN ('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'SUSPENDED')),
    CONSTRAINT employees_employment_type_check CHECK (employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN'))
);

ALTER TABLE employees ADD COLUMN IF NOT EXISTS reporting_manager_id BIGINT REFERENCES employees(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS employee_approval_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requested_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    employee_data JSONB NOT NULL,
    password_hash TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    reviewed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at TIMESTAMPTZ,
    review_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT employee_approval_requests_status_check
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

ALTER TABLE employee_approval_requests
    ALTER COLUMN password_hash DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_employee_approval_requests_pending_email
    ON employee_approval_requests (LOWER(employee_data->>'email'))
    WHERE status = 'PENDING';

-- Campaigns Table
CREATE TABLE IF NOT EXISTS campaigns (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_code     VARCHAR(40) NOT NULL UNIQUE,
    campaign_name     VARCHAR(200) NOT NULL,
    platform          VARCHAR(100),
    source            VARCHAR(100),
    budget            NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (budget >= 0),
    landing_page_url  TEXT,
    description       TEXT,
    start_date        DATE,
    end_date          DATE,
    status            VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_by        BIGINT,
    updated_by        BIGINT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted        BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT campaigns_dates_check CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT campaigns_status_check CHECK (status IN ('ACTIVE', 'INACTIVE', 'COMPLETED', 'DRAFT'))
);

-- Leads Table
CREATE TABLE IF NOT EXISTS leads (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_code           VARCHAR(40) NOT NULL UNIQUE,
    campaign_id         BIGINT REFERENCES campaigns(id) ON DELETE SET NULL,
    domain              VARCHAR(150),
    full_name           VARCHAR(150) NOT NULL,
    mobile              VARCHAR(20) NOT NULL,
    alternate_mobile    VARCHAR(20),
    phone               VARCHAR(20),
    email               VARCHAR(255),
    city                VARCHAR(100),
    state               VARCHAR(100),
    country             VARCHAR(100) NOT NULL DEFAULT 'India',
    interested_course   VARCHAR(200),
    preferred_centre    VARCHAR(200),
    source              VARCHAR(100) NOT NULL,
    platform            VARCHAR(100),
    landing_page_url    TEXT,
    utm_source          VARCHAR(255),
    utm_medium          VARCHAR(255),
    utm_campaign        VARCHAR(255),
    utm_content         VARCHAR(255),
    utm_term            VARCHAR(255),
    external_lead_id    VARCHAR(255),
    status              VARCHAR(30) NOT NULL DEFAULT 'NEW',
    priority            VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    assigned_to         BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    assignment_mode     VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    routing_rule_description TEXT,
    remarks             TEXT,
    feedback            TEXT,
    next_followup       TIMESTAMPTZ,
    is_duplicate        BOOLEAN NOT NULL DEFAULT FALSE,
    duplicate_of        BIGINT,
    received_count      INTEGER NOT NULL DEFAULT 1,
    first_source        VARCHAR(100),
    previous_source     VARCHAR(100),
    source_history      JSONB DEFAULT '[]'::jsonb,
    last_received_at    TIMESTAMPTZ,
    captured_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          BIGINT,
    updated_by          BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT leads_status_check CHECK (
      UPPER(status) IN (
        'NEW', 'INTERESTED', 'FOLLOW_UP', 'VISITED', 'ENROLLED', 'NOT_INTERESTED',
        'CONTACTED', 'QUALIFIED', 'ADMISSION_DONE', 'LOST', 'PENDING', 'COMPLETED', 'REJECTED'
      )
    ),
    CONSTRAINT leads_priority_check CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'low', 'medium', 'high'))
);

ALTER TABLE leads ADD COLUMN IF NOT EXISTS domain VARCHAR(150);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS assignment_mode VARCHAR(20) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS routing_rule_description TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS first_source VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS previous_source VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS source_history JSONB DEFAULT '[]'::jsonb;

ALTER TABLE leads DROP CONSTRAINT IF EXISTS leads_assignment_mode_check;
ALTER TABLE leads
    ADD CONSTRAINT leads_assignment_mode_check
    CHECK (assignment_mode IN ('MANUAL', 'AUTO'));

-- Lead Sources Table
CREATE TABLE IF NOT EXISTS lead_sources (
    id          SERIAL PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT,
    is_active   BOOLEAN DEFAULT TRUE,
    is_deleted  BOOLEAN DEFAULT FALSE,
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Lead Domains Table
CREATE TABLE IF NOT EXISTS lead_domains (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL UNIQUE,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE lead_domains
    ADD COLUMN IF NOT EXISTS caller_id VARCHAR(32),
    ADD COLUMN IF NOT EXISTS virtual_number VARCHAR(32);

-- Domain Courses Table
CREATE TABLE IF NOT EXISTS domain_courses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id   BIGINT NOT NULL REFERENCES lead_domains(id) ON DELETE CASCADE,
    name        VARCHAR(200) NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (domain_id, name)
);

-- Counsellor Routing Assignments Table
CREATE TABLE IF NOT EXISTS counsellor_routing_assignments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id       BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    domain_id         BIGINT NOT NULL REFERENCES lead_domains(id) ON DELETE CASCADE,
    course_id         BIGINT REFERENCES domain_courses(id) ON DELETE CASCADE,
    auto_assign       BOOLEAN NOT NULL DEFAULT TRUE,
    is_active         BOOLEAN NOT NULL DEFAULT TRUE,
    last_assigned_at  TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE NULLS NOT DISTINCT (employee_id, domain_id, course_id)
);

-- Admissions Table
CREATE TABLE IF NOT EXISTS admissions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_code      VARCHAR(40) NOT NULL UNIQUE,
    lead_id             BIGINT REFERENCES leads(id) ON DELETE SET NULL,
    student_name        VARCHAR(150) NOT NULL,
    mobile              VARCHAR(20) NOT NULL,
    email               VARCHAR(255),
    course_name         VARCHAR(200) NOT NULL,
    campus_centre       VARCHAR(200),
    total_fee           NUMERIC(14, 2) NOT NULL DEFAULT 0,
    paid_fee            NUMERIC(14, 2) NOT NULL DEFAULT 0,
    pending_fee         NUMERIC(14, 2) NOT NULL DEFAULT 0,
    receipt_no          VARCHAR(100),
    payment_mode        VARCHAR(50) DEFAULT 'CASH',
    next_due_date       DATE,
    status              VARCHAR(30) NOT NULL DEFAULT 'ENROLLED',
    assigned_to         BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    remarks             TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Lead Assignments Table
CREATE TABLE IF NOT EXISTS lead_assignments (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id               BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    assigned_by           BIGINT,
    assigned_to           BIGINT NOT NULL,
    previous_assigned_to  BIGINT,
    remarks               TEXT,
    assigned_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Lead Followups Table
CREATE TABLE IF NOT EXISTS lead_followups (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id             BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    employee_id         BIGINT NOT NULL,
    followup_type       VARCHAR(30) NOT NULL DEFAULT 'CALL',
    status              VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    outcome             VARCHAR(100),
    priority            VARCHAR(20) DEFAULT 'MEDIUM',
    next_followup_at    TIMESTAMPTZ,
    remarks             TEXT,
    created_by          BIGINT,
    updated_by          BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ,
    deleted_by          BIGINT,
    CONSTRAINT lead_followups_type_check CHECK (followup_type IN ('CALL', 'WHATSAPP', 'EMAIL', 'SMS', 'MEETING', 'OTHER')),
    CONSTRAINT lead_followups_status_check CHECK (status IN ('PENDING', 'COMPLETED', 'CANCELLED', 'MISSED', 'RESCHEDULED')),
    CONSTRAINT lead_followups_priority_check CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
);

-- Lead Notes Table
CREATE TABLE IF NOT EXISTS lead_notes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id         BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    note            TEXT NOT NULL,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lead_feedback (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id             BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    status_at_feedback  VARCHAR(50) NOT NULL,
    feedback_fields     JSONB NOT NULL DEFAULT '{}'::jsonb,
    remarks             TEXT,
    created_by          BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Lead Timeline Table
CREATE TABLE IF NOT EXISTS lead_timeline (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id         BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    employee_id     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    activity_type   VARCHAR(100),
    title           VARCHAR(255),
    description     TEXT,
    old_value       TEXT,
    new_value       TEXT,
    action          VARCHAR(100),
    remarks         TEXT,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Cloud click-to-call history and provider recording metadata
CREATE TABLE IF NOT EXISTS lead_call_logs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id             BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    employee_id         BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    call_sid            VARCHAR(255) NOT NULL UNIQUE,
    provider            VARCHAR(32) NOT NULL,
    counsellor_number   VARCHAR(32),
    lead_number         VARCHAR(32),
    caller_id           VARCHAR(32),
    status              VARCHAR(32) NOT NULL DEFAULT 'INITIATED',
    duration            INTEGER NOT NULL DEFAULT 0 CHECK (duration >= 0),
    recording_duration  INTEGER NOT NULL DEFAULT 0 CHECK (recording_duration >= 0),
    recording_url       TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_lead_call_logs_lead_created
    ON lead_call_logs (lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lead_call_logs_employee_created
    ON lead_call_logs (employee_id, created_at DESC);

-- Lead Activity Logs Table
CREATE TABLE IF NOT EXISTS lead_activity_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id         BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    activity        VARCHAR(100) NOT NULL,
    description     TEXT,
    performed_by    BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Refresh Tokens Table
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token           TEXT NOT NULL UNIQUE,
    expires_at      TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Password Resets Table
CREATE TABLE IF NOT EXISTS password_resets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reset_token     TEXT NOT NULL UNIQUE,
    expires_at      TIMESTAMPTZ NOT NULL,
    used            BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    actor_user_id   BIGINT REFERENCES users(id) ON DELETE SET NULL,
    type            VARCHAR(80) NOT NULL,
    category        VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    title           VARCHAR(255) NOT NULL,
    message         TEXT NOT NULL,
    link            VARCHAR(255),
    priority        VARCHAR(20) NOT NULL DEFAULT 'INFO',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_notifications_recipient_created
    ON user_notifications (user_id, created_at DESC);

-- Final role constraints from the current role migrations
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users
    ADD CONSTRAINT users_role_check CHECK (role IN (
        'ADMIN', 'SUPER_ADMIN', 'MANAGER', 'COUNSELLOR', 'EMPLOYEE',
        'HR', 'TL', 'TRAINER', 'INTERN',
        'admin', 'super_admin', 'manager', 'counsellor', 'employee',
        'hr', 'tl', 'trainer', 'intern'
    ));

ALTER TABLE employees DROP CONSTRAINT IF EXISTS employees_role_check;
ALTER TABLE employees
    ADD CONSTRAINT employees_role_check CHECK (role IN (
        'ADMIN', 'SUPER_ADMIN', 'MANAGER', 'COUNSELLOR', 'EMPLOYEE',
        'HR', 'TL', 'TRAINER', 'INTERN'
    ));

-- Required reference data; conflict-safe for existing databases
INSERT INTO departments (department_name, description, status)
VALUES
    ('Sales', 'Sales, lead follow-up, counselling and admissions conversion', TRUE),
    ('Operations', 'Daily business operations, coordination and service delivery', TRUE),
    ('Academics & Training', 'Institute trainers, mentors, lecture classes and student sessions', TRUE),
    ('Digital Marketing & Agency', 'Performance marketing, Meta ads, Google ads, SEO & client services', TRUE),
    ('Web & Tech Development', 'CRM development, web development and IT infrastructure', TRUE),
    ('Graphic Design & Video Editing', 'Creative media, class materials, marketing creatives and video production', TRUE),
    ('Human Resources (HR)', 'Recruitment, employee compliance, team classes and daily operational reporting', TRUE),
    ('Operations & Administration', 'Company operations, facilities and student coordination', TRUE)
ON CONFLICT (department_name) DO UPDATE
    SET description = EXCLUDED.description, status = TRUE;

INSERT INTO lead_sources (name, description, is_active)
VALUES
    ('Website', 'Captured via website form', TRUE),
    ('Google Ads', 'Paid search campaigns', TRUE),
    ('Meta', 'Meta / Facebook campaigns', TRUE),
    ('Referral', 'Referred by partner or student', TRUE),
    ('Walk In', 'Direct walk in enquiry', TRUE),
    ('Main Website', 'Official institute & agency main website', TRUE)
ON CONFLICT (name) DO UPDATE
    SET is_active = TRUE, is_deleted = FALSE;

-- Rename the legacy domain only when the canonical row does not already exist.
UPDATE lead_domains legacy
SET name = 'Nipage', updated_at = CURRENT_TIMESTAMP
WHERE legacy.name = 'Nigape'
  AND NOT EXISTS (
      SELECT 1 FROM lead_domains canonical WHERE canonical.name = 'Nipage'
  );

UPDATE leads
SET domain = 'Nipage', updated_at = CURRENT_TIMESTAMP
WHERE LOWER(domain) = 'nigape';

INSERT INTO lead_domains (name, is_active)
VALUES
    ('DizitalAdda', TRUE),
    ('Nidads', TRUE),
    ('Nipage', TRUE),
    ('Nihacs', TRUE),
    ('HackingVidya', TRUE),
    ('IIDAD', TRUE),
    ('Nifase', TRUE),
    ('DesigningVidya', TRUE),
    ('LanguageVidya', TRUE),
    ('www.nidads.com', TRUE),
    ('www.nipage.com', TRUE),
    ('www.iidad.com', TRUE)
ON CONFLICT (name) DO UPDATE SET is_active = TRUE;

-- Daily work reports and class/video logs
ALTER TABLE employees
    ADD COLUMN IF NOT EXISTS reporting_manager_id BIGINT REFERENCES employees(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS daily_work_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    employee_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    report_date DATE NOT NULL DEFAULT CURRENT_DATE,
    role_type VARCHAR(50) NOT NULL DEFAULT 'EMPLOYEE',
    work_title VARCHAR(255),
    tasks_summary TEXT NOT NULL,
    total_hours_worked NUMERIC(4, 2) NOT NULL DEFAULT 8.00,
    work_status VARCHAR(50) NOT NULL DEFAULT 'COMPLETED',
    deliverable_links TEXT,
    blockers TEXT,
    next_day_plan TEXT,
    took_class BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(50) NOT NULL DEFAULT 'SUBMITTED',
    tl_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    tl_feedback TEXT,
    tl_reviewed_at TIMESTAMPTZ,
    hr_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    hr_feedback TEXT,
    hr_reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_user_report_date UNIQUE (user_id, report_date),
    CONSTRAINT chk_report_status CHECK (status IN ('SUBMITTED', 'TL_REVIEWED', 'HR_APPROVED', 'REVISION_REQUESTED'))
);

CREATE TABLE IF NOT EXISTS work_report_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL REFERENCES daily_work_reports(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    batch_name VARCHAR(150) NOT NULL,
    course_name VARCHAR(150),
    topic_covered VARCHAR(255) NOT NULL,
    class_time_start VARCHAR(50),
    class_time_end VARCHAR(50),
    duration_minutes INT DEFAULT 60,
    students_count INT DEFAULT 0,
    video_recording_url TEXT NOT NULL,
    materials_url TEXT,
    remarks TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_employees_active_department ON employees (department_id) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_campaigns_active_status ON campaigns (status) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_leads_active_assigned_to ON leads (assigned_to) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_leads_active_status ON leads (status) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_leads_campaign_id ON leads (campaign_id);
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads (created_at DESC) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_lead_assignments_lead_id ON lead_assignments (lead_id, assigned_at DESC);
CREATE INDEX IF NOT EXISTS idx_followups_due ON lead_followups (employee_id, next_followup_at) WHERE is_deleted = FALSE AND status = 'PENDING';
CREATE INDEX IF NOT EXISTS idx_followups_lead_id ON lead_followups (lead_id);
CREATE INDEX IF NOT EXISTS idx_timeline_lead_id ON lead_timeline (lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lead_notes_lead_id ON lead_notes (lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
CREATE INDEX IF NOT EXISTS idx_password_resets_token ON password_resets (reset_token) WHERE used = FALSE;
CREATE INDEX IF NOT EXISTS idx_admissions_lead_id ON admissions (lead_id);
CREATE INDEX IF NOT EXISTS idx_admissions_assigned_to ON admissions (assigned_to);
CREATE INDEX IF NOT EXISTS idx_lead_feedback_lead_id ON lead_feedback (lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_domain_courses_domain_id ON domain_courses (domain_id) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_counsellor_routing_lookup
    ON counsellor_routing_assignments (domain_id, course_id, last_assigned_at)
    WHERE is_active = TRUE AND auto_assign = TRUE;
CREATE INDEX IF NOT EXISTS idx_work_reports_date ON daily_work_reports (report_date);
CREATE INDEX IF NOT EXISTS idx_work_reports_user ON daily_work_reports (user_id);
CREATE INDEX IF NOT EXISTS idx_work_reports_dept ON daily_work_reports (department_id);
CREATE INDEX IF NOT EXISTS idx_work_reports_status ON daily_work_reports (status);
CREATE INDEX IF NOT EXISTS idx_report_classes_report ON work_report_classes (report_id);
CREATE INDEX IF NOT EXISTS idx_report_classes_user ON work_report_classes (user_id);

COMMIT;
