-- =====================================================
-- DIZITALADDA CRM - Clean Database Schema (DDL Only)
-- PostgreSQL 15+ / 16+ Compatible
-- Contains only structure, tables, constraints, and indexes.
-- NO hardcoded data, values, or credentials.
-- =====================================================

BEGIN;

-- Code Generation Sequences
CREATE SEQUENCE IF NOT EXISTS employee_code_seq START WITH 1001;
CREATE SEQUENCE IF NOT EXISTS campaign_code_seq START WITH 1001;
CREATE SEQUENCE IF NOT EXISTS lead_code_seq START WITH 1001;

-- Users Table
CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR(150) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    role            VARCHAR(30) NOT NULL DEFAULT 'COUNSELLOR',
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,
    email_verified  BOOLEAN NOT NULL DEFAULT FALSE,
    profile_image   TEXT,
    last_login      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'MANAGER', 'COUNSELLOR', 'EMPLOYEE', 'admin', 'manager', 'counsellor', 'employee'))
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image TEXT;

-- Departments Table
CREATE TABLE IF NOT EXISTS departments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(150) NOT NULL UNIQUE,
    description     TEXT,
    status          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Employees Table
CREATE TABLE IF NOT EXISTS employees (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT UNIQUE REFERENCES users(id) ON DELETE SET NULL,
    employee_code           VARCHAR(30) NOT NULL UNIQUE,
    full_name               VARCHAR(150) NOT NULL,
    email                   VARCHAR(255) NOT NULL UNIQUE,
    mobile                  VARCHAR(20) NOT NULL UNIQUE,
    department_id           BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    designation             VARCHAR(100),
    role                    VARCHAR(30) NOT NULL DEFAULT 'COUNSELLOR',
    employment_type         VARCHAR(30) NOT NULL DEFAULT 'FULL_TIME',
    status                  VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    joining_date            DATE,
    date_of_birth           DATE,
    gender                  VARCHAR(30),
    profile_image           TEXT,
    address                 TEXT,
    emergency_contact_name  VARCHAR(150),
    emergency_contact       VARCHAR(20),
    domain                  VARCHAR(150),
    assigned_domains        JSONB DEFAULT '[]'::jsonb,
    created_by              BIGINT,
    updated_by              BIGINT,
    deleted_by              BIGINT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at              TIMESTAMPTZ,
    is_deleted              BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT employees_role_check CHECK (role IN ('ADMIN', 'MANAGER', 'COUNSELLOR', 'EMPLOYEE')),
    CONSTRAINT employees_status_check CHECK (status IN ('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'SUSPENDED')),
    CONSTRAINT employees_employment_type_check CHECK (employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN'))
);

-- Campaigns Table
CREATE TABLE IF NOT EXISTS campaigns (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_code     VARCHAR(40) NOT NULL UNIQUE,
    campaign_name     VARCHAR(200) NOT NULL,
    platform          VARCHAR(100),
    source            VARCHAR(100),
    budget            NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (budget >= 0),
    landing_page_url  TEXT,
    description       TEXT,
    start_date        DATE,
    end_date          DATE,
    status            VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_by        BIGINT,
    updated_by        BIGINT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted        BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT campaigns_dates_check CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT campaigns_status_check CHECK (status IN ('ACTIVE', 'INACTIVE', 'COMPLETED', 'DRAFT'))
);

-- Leads Table
CREATE TABLE IF NOT EXISTS leads (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_code           VARCHAR(40) NOT NULL UNIQUE,
    campaign_id         BIGINT REFERENCES campaigns(id) ON DELETE SET NULL,
    domain              VARCHAR(150),
    full_name           VARCHAR(150) NOT NULL,
    mobile              VARCHAR(20) NOT NULL,
    alternate_mobile    VARCHAR(20),
    phone               VARCHAR(20),
    email               VARCHAR(255),
    city                VARCHAR(100),
    state               VARCHAR(100),
    country             VARCHAR(100) NOT NULL DEFAULT 'India',
    interested_course   VARCHAR(200),
    preferred_centre    VARCHAR(200),
    source              VARCHAR(100) NOT NULL,
    platform            VARCHAR(100),
    landing_page_url    TEXT,
    utm_source          VARCHAR(255),
    utm_medium          VARCHAR(255),
    utm_campaign        VARCHAR(255),
    utm_content         VARCHAR(255),
    utm_term            VARCHAR(255),
    external_lead_id    VARCHAR(255),
    status              VARCHAR(30) NOT NULL DEFAULT 'NEW',
    priority            VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    assigned_to         BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    assignment_mode     VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    routing_rule_description TEXT,
    remarks             TEXT,
    feedback            TEXT,
    next_followup       TIMESTAMPTZ,
    is_duplicate        BOOLEAN NOT NULL DEFAULT FALSE,
    duplicate_of        BIGINT,
    received_count      INTEGER NOT NULL DEFAULT 1,
    first_source        VARCHAR(100),
    previous_source     VARCHAR(100),
    source_history      JSONB DEFAULT '[]'::jsonb,
    last_received_at    TIMESTAMPTZ,
    captured_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          BIGINT,
    updated_by          BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT leads_status_check CHECK (
      UPPER(status) IN (
        'NEW', 'INTERESTED', 'FOLLOW_UP', 'VISITED', 'ENROLLED', 'NOT_INTERESTED',
        'CONTACTED', 'QUALIFIED', 'ADMISSION_DONE', 'LOST', 'PENDING', 'COMPLETED', 'REJECTED'
      )
    ),
    CONSTRAINT leads_priority_check CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'low', 'medium', 'high'))
);

-- Lead Sources Table
CREATE TABLE IF NOT EXISTS lead_sources (
    id          SERIAL PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT,
    is_active   BOOLEAN DEFAULT TRUE,
    is_deleted  BOOLEAN DEFAULT FALSE,
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Lead Domains Table
CREATE TABLE IF NOT EXISTS lead_domains (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL UNIQUE,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Domain Courses Table
CREATE TABLE IF NOT EXISTS domain_courses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id   BIGINT NOT NULL REFERENCES lead_domains(id) ON DELETE CASCADE,
    name        VARCHAR(200) NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (domain_id, name)
);

-- Counsellor Routing Assignments Table
CREATE TABLE IF NOT EXISTS counsellor_routing_assignments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id       BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    domain_id         BIGINT NOT NULL REFERENCES lead_domains(id) ON DELETE CASCADE,
    course_id         BIGINT REFERENCES domain_courses(id) ON DELETE CASCADE,
    auto_assign       BOOLEAN NOT NULL DEFAULT TRUE,
    is_active         BOOLEAN NOT NULL DEFAULT TRUE,
    last_assigned_at  TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE NULLS NOT DISTINCT (employee_id, domain_id, course_id)
);

-- Admissions Table
CREATE TABLE IF NOT EXISTS admissions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_code      VARCHAR(40) NOT NULL UNIQUE,
    lead_id             BIGINT REFERENCES leads(id) ON DELETE SET NULL,
    student_name        VARCHAR(150) NOT NULL,
    mobile              VARCHAR(20) NOT NULL,
    email               VARCHAR(255),
    course_name         VARCHAR(200) NOT NULL,
    campus_centre       VARCHAR(200),
    total_fee           NUMERIC(14, 2) NOT NULL DEFAULT 0,
    paid_fee            NUMERIC(14, 2) NOT NULL DEFAULT 0,
    pending_fee         NUMERIC(14, 2) NOT NULL DEFAULT 0,
    receipt_no          VARCHAR(100),
    payment_mode        VARCHAR(50) DEFAULT 'CASH',
    next_due_date       DATE,
    status              VARCHAR(30) NOT NULL DEFAULT 'ENROLLED',
    assigned_to         BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    remarks             TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Lead Assignments Table
CREATE TABLE IF NOT EXISTS lead_assignments (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id               BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    assigned_by           BIGINT,
    assigned_to           BIGINT NOT NULL,
    previous_assigned_to  BIGINT,
    remarks               TEXT,
    assigned_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Lead Followups Table
CREATE TABLE IF NOT EXISTS lead_followups (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id             BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    employee_id         BIGINT NOT NULL,
    followup_type       VARCHAR(30) NOT NULL DEFAULT 'CALL',
    status              VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    outcome             VARCHAR(100),
    priority            VARCHAR(20) DEFAULT 'MEDIUM',
    next_followup_at    TIMESTAMPTZ,
    remarks             TEXT,
    created_by          BIGINT,
    updated_by          BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ,
    deleted_by          BIGINT,
    CONSTRAINT lead_followups_type_check CHECK (followup_type IN ('CALL', 'WHATSAPP', 'EMAIL', 'SMS', 'MEETING', 'OTHER')),
    CONSTRAINT lead_followups_status_check CHECK (status IN ('PENDING', 'COMPLETED', 'CANCELLED', 'MISSED', 'RESCHEDULED')),
    CONSTRAINT lead_followups_priority_check CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
);

-- Lead Notes Table
CREATE TABLE IF NOT EXISTS lead_notes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id         BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    note            TEXT NOT NULL,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Lead Timeline Table
CREATE TABLE IF NOT EXISTS lead_timeline (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id         BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    employee_id     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    activity_type   VARCHAR(100),
    title           VARCHAR(255),
    description     TEXT,
    old_value       TEXT,
    new_value       TEXT,
    action          VARCHAR(100),
    remarks         TEXT,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Lead Activity Logs Table
CREATE TABLE IF NOT EXISTS lead_activity_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id         BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    activity        VARCHAR(100) NOT NULL,
    description     TEXT,
    performed_by    BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Refresh Tokens Table
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token           TEXT NOT NULL UNIQUE,
    expires_at      TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Password Resets Table
CREATE TABLE IF NOT EXISTS password_resets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reset_token     TEXT NOT NULL UNIQUE,
    expires_at      TIMESTAMPTZ NOT NULL,
    used            BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_employees_active_department ON employees (department_id) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_campaigns_active_status ON campaigns (status) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_leads_active_assigned_to ON leads (assigned_to) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_leads_active_status ON leads (status) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_leads_campaign_id ON leads (campaign_id);
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads (created_at DESC) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_lead_assignments_lead_id ON lead_assignments (lead_id, assigned_at DESC);
CREATE INDEX IF NOT EXISTS idx_followups_due ON lead_followups (employee_id, next_followup_at) WHERE is_deleted = FALSE AND status = 'PENDING';
CREATE INDEX IF NOT EXISTS idx_followups_lead_id ON lead_followups (lead_id);
CREATE INDEX IF NOT EXISTS idx_timeline_lead_id ON lead_timeline (lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lead_notes_lead_id ON lead_notes (lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
CREATE INDEX IF NOT EXISTS idx_password_resets_token ON password_resets (reset_token) WHERE used = FALSE;
CREATE INDEX IF NOT EXISTS idx_admissions_lead_id ON admissions (lead_id);
CREATE INDEX IF NOT EXISTS idx_admissions_assigned_to ON admissions (assigned_to);

COMMIT;
