BEGIN;

ALTER TABLE lead_domains
  ADD COLUMN IF NOT EXISTS caller_id VARCHAR(32),
  ADD COLUMN IF NOT EXISTS virtual_number VARCHAR(32);

CREATE TABLE IF NOT EXISTS lead_call_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  employee_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  call_sid VARCHAR(255) NOT NULL UNIQUE,
  provider VARCHAR(32) NOT NULL,
  counsellor_number VARCHAR(32),
  lead_number VARCHAR(32),
  caller_id VARCHAR(32),
  status VARCHAR(32) NOT NULL DEFAULT 'INITIATED',
  duration INTEGER NOT NULL DEFAULT 0 CHECK (duration >= 0),
  recording_duration INTEGER NOT NULL DEFAULT 0 CHECK (recording_duration >= 0),
  recording_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_lead_call_logs_lead_created
  ON lead_call_logs (lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lead_call_logs_employee_created
  ON lead_call_logs (employee_id, created_at DESC);

COMMIT;
