BEGIN;

CREATE TABLE IF NOT EXISTS daily_employee_work_modes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
  work_date DATE NOT NULL DEFAULT CURRENT_DATE,
  work_mode VARCHAR(10) NOT NULL DEFAULT 'OFFICE'
    CHECK (work_mode IN ('OFFICE', 'WFH')),
  updated_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (employee_id, work_date)
);

CREATE INDEX IF NOT EXISTS idx_daily_employee_work_modes_date
  ON daily_employee_work_modes (work_date, work_mode);

COMMIT;
