-- =====================================================
-- DIZITALADDA CRM - Daily Work Reporting & Class Logs
-- Multi-Tier Operations & HR Reporting System
-- =====================================================

BEGIN;

-- 1. Update users role check constraint to support HR, TL, TRAINER, INTERN
DO $$
BEGIN
    ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
    ALTER TABLE users ADD CONSTRAINT users_role_check 
        CHECK (role IN (
            'ADMIN', 'SUPER_ADMIN', 'MANAGER', 'COUNSELLOR', 'EMPLOYEE',
            'HR', 'TL', 'TRAINER', 'INTERN',
            'admin', 'super_admin', 'manager', 'counsellor', 'employee',
            'hr', 'tl', 'trainer', 'intern'
        ));
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Constraint users_role_check update notice: %', SQLERRM;
END $$;

-- 2. Update employees role check constraint
DO $$
BEGIN
    ALTER TABLE employees DROP CONSTRAINT IF EXISTS employees_role_check;
    ALTER TABLE employees ADD CONSTRAINT employees_role_check 
        CHECK (role IN (
            'ADMIN', 'SUPER_ADMIN', 'MANAGER', 'COUNSELLOR', 'EMPLOYEE',
            'HR', 'TL', 'TRAINER', 'INTERN'
        ));
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Constraint employees_role_check update notice: %', SQLERRM;
END $$;

-- 3. Add reporting_manager_id to employees to link Employee/Intern -> TL
ALTER TABLE employees ADD COLUMN IF NOT EXISTS reporting_manager_id BIGINT REFERENCES employees(id) ON DELETE SET NULL;

-- 4. Seed Standard Operational Departments if not exist
INSERT INTO departments (department_name, description, status)
VALUES 
    ('Academics & Training', 'Institute trainers, mentors, lecture classes and student sessions', true),
    ('Digital Marketing & Agency', 'Performance marketing, Meta ads, Google ads, SEO & client services', true),
    ('Web & Tech Development', 'CRM development, web development and IT infrastructure', true),
    ('Graphic Design & Video Editing', 'Creative media, class materials, marketing creatives and video production', true),
    ('Human Resources (HR)', 'Recruitment, employee compliance, team classes and daily operational reporting', true),
    ('Operations & Administration', 'Company operations, facilities and student coordination', true)
ON CONFLICT (department_name) DO UPDATE 
    SET description = EXCLUDED.description, status = true;

-- 5. Create daily_work_reports Table
CREATE TABLE IF NOT EXISTS daily_work_reports (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    employee_id             BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    department_id           BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    report_date             DATE NOT NULL DEFAULT CURRENT_DATE,
    role_type               VARCHAR(50) NOT NULL DEFAULT 'EMPLOYEE',
    work_title              VARCHAR(255),
    tasks_summary           TEXT NOT NULL,
    total_hours_worked      NUMERIC(4, 2) NOT NULL DEFAULT 8.00,
    work_status             VARCHAR(50) NOT NULL DEFAULT 'COMPLETED',
    deliverable_links       TEXT,
    blockers                TEXT,
    next_day_plan           TEXT,
    took_class              BOOLEAN NOT NULL DEFAULT FALSE,
    status                  VARCHAR(50) NOT NULL DEFAULT 'SUBMITTED',
    tl_id                   BIGINT REFERENCES users(id) ON DELETE SET NULL,
    tl_feedback             TEXT,
    tl_reviewed_at          TIMESTAMPTZ,
    hr_id                   BIGINT REFERENCES users(id) ON DELETE SET NULL,
    hr_feedback             TEXT,
    hr_reviewed_at          TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_user_report_date UNIQUE (user_id, report_date),
    CONSTRAINT chk_report_status CHECK (status IN ('SUBMITTED', 'TL_REVIEWED', 'HR_APPROVED', 'REVISION_REQUESTED'))
);

CREATE INDEX IF NOT EXISTS idx_work_reports_date ON daily_work_reports(report_date);
CREATE INDEX IF NOT EXISTS idx_work_reports_user ON daily_work_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_work_reports_dept ON daily_work_reports(department_id);
CREATE INDEX IF NOT EXISTS idx_work_reports_status ON daily_work_reports(status);

-- 6. Create work_report_classes Table (For Trainer / Mentor / HR class logs with Video Proof)
CREATE TABLE IF NOT EXISTS work_report_classes (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id               BIGINT NOT NULL REFERENCES daily_work_reports(id) ON DELETE CASCADE,
    user_id                 BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    batch_name              VARCHAR(150) NOT NULL,
    course_name             VARCHAR(150),
    topic_covered           VARCHAR(255) NOT NULL,
    class_time_start        VARCHAR(50),
    class_time_end          VARCHAR(50),
    duration_minutes        INT DEFAULT 60,
    students_count          INT DEFAULT 0,
    video_recording_url     TEXT NOT NULL,
    materials_url           TEXT,
    remarks                 TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_report_classes_report ON work_report_classes(report_id);
CREATE INDEX IF NOT EXISTS idx_report_classes_user ON work_report_classes(user_id);

COMMIT;
