CREATE TABLE IF NOT EXISTS employee_leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL,
  leave_type VARCHAR(20) NOT NULL CHECK (leave_type IN ('PLANNED', 'URGENT')),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason TEXT NOT NULL,
  status VARCHAR(40) NOT NULL CHECK (
    status IN ('PENDING_DEPARTMENT_HEAD', 'PENDING_HR_APPROVAL', 'APPROVED', 'REJECTED')
  ),
  department_head_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  department_head_reviewed_at TIMESTAMPTZ,
  hr_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  hr_reviewed_at TIMESTAMPTZ,
  rejection_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS idx_employee_leave_requests_user_created
  ON employee_leave_requests (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_employee_leave_requests_status_department
  ON employee_leave_requests (status, department_id);
