BEGIN;

CREATE TABLE IF NOT EXISTS daily_employee_presence_overrides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  presence_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status VARCHAR(20) NOT NULL CHECK (status IN ('ON_LEAVE')),
  updated_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (employee_id, presence_date)
);

CREATE INDEX IF NOT EXISTS idx_daily_employee_presence_overrides_date
  ON daily_employee_presence_overrides (presence_date, status);

COMMIT;
