BEGIN;

CREATE TABLE IF NOT EXISTS user_devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  device_id UUID NOT NULL,
  device_type VARCHAR(10) NOT NULL CHECK (device_type IN ('laptop', 'mobile')),
  device_name VARCHAR(120) NOT NULL,
  user_agent TEXT,
  ip_address TEXT,
  status VARCHAR(10) NOT NULL DEFAULT 'approved'
    CHECK (status IN ('approved', 'revoked')),
  first_seen TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  revoked_at TIMESTAMPTZ,
  UNIQUE (user_id, device_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_devices_approved_slot
  ON user_devices (user_id, device_type)
  WHERE status = 'approved';

CREATE INDEX IF NOT EXISTS idx_user_devices_user_last_seen
  ON user_devices (user_id, last_seen DESC);

CREATE TABLE IF NOT EXISTS blocked_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  device_id UUID NOT NULL,
  device_type VARCHAR(10) NOT NULL CHECK (device_type IN ('laptop', 'mobile')),
  ip_address TEXT,
  user_agent TEXT,
  attempted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_blocked_attempts_user_attempted
  ON blocked_attempts (user_id, attempted_at DESC);

CREATE TABLE IF NOT EXISTS device_admin_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  employee_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  action VARCHAR(40) NOT NULL,
  device_id UUID,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  ip_address TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_device_admin_audit_employee_created
  ON device_admin_audit_logs (employee_user_id, created_at DESC);

ALTER TABLE refresh_tokens
  ADD COLUMN IF NOT EXISTS device_id UUID;

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_device_id
  ON refresh_tokens (device_id);

COMMIT;
