BEGIN;

-- 1. Ensure users table supports direct reports_to and department_id alongside employees table
ALTER TABLE users ADD COLUMN IF NOT EXISTS reports_to BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_users_reports_to ON users(reports_to) WHERE is_deleted = FALSE;

-- 2. Extend daily_work_reports with hierarchical tracking columns
ALTER TABLE daily_work_reports ADD COLUMN IF NOT EXISTS report_type VARCHAR(20) NOT NULL DEFAULT 'DAILY';
ALTER TABLE daily_work_reports ADD COLUMN IF NOT EXISTS current_status VARCHAR(40) NOT NULL DEFAULT 'PENDING';
ALTER TABLE daily_work_reports ADD COLUMN IF NOT EXISTS current_level_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE daily_work_reports ADD COLUMN IF NOT EXISTS current_approval_level INTEGER;

CREATE INDEX IF NOT EXISTS idx_daily_work_reports_current_approver
  ON daily_work_reports(current_level_user_id, status);

-- 3. Create report_approvals table for multi-level approval & skip/auto-approval audit trail
CREATE TABLE IF NOT EXISTS report_approvals (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id         BIGINT NOT NULL REFERENCES daily_work_reports(id) ON DELETE CASCADE,
  approver_id       BIGINT REFERENCES users(id) ON DELETE SET NULL,
  acted_by_id       BIGINT REFERENCES users(id) ON DELETE SET NULL,
  level             INTEGER NOT NULL,
  role_label        VARCHAR(50) NOT NULL,
  status            VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  remarks           TEXT,
  is_auto_approved  BOOLEAN NOT NULL DEFAULT FALSE,
  acted_at          TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (report_id, level)
);

CREATE INDEX IF NOT EXISTS idx_report_approvals_report_level
  ON report_approvals(report_id, level ASC);

CREATE INDEX IF NOT EXISTS idx_report_approvals_approver_status
  ON report_approvals(approver_id, status);

COMMIT;
